# Generated by Django 2.2 on 2020-02-13 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.TextField(verbose_name='ACT类别')),
                ('actid', models.TextField(verbose_name='话语行为类别')),
            ],
        ),
        migrations.CreateModel(
            name='LabelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelid', models.IntegerField(verbose_name='BIO类别')),
                ('labelmeaning', models.TextField(verbose_name='BIO含义')),
            ],
        ),
        migrations.CreateModel(
            name='RawText',
            fields=[
                ('unique_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='样本句子序号')),
                ('example_id', models.IntegerField(verbose_name='样本序号')),
                ('sentence_id', models.IntegerField(verbose_name='句子序号')),
                ('speaker', models.TextField(verbose_name='对话人')),
                ('sentence', models.TextField(null=True, verbose_name='对话文本')),
                ('label', models.CharField(max_length=300, null=True, verbose_name='预设标签')),
                ('normalized', models.CharField(max_length=128, null=True, verbose_name='归一化症状标签')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='症状判断')),
                ('drug_word', models.CharField(max_length=128, null=True, verbose_name='药品判断')),
                ('drug_pos', models.CharField(max_length=128, null=True, verbose_name='药品位置')),
                ('check_word', models.CharField(max_length=128, null=True, verbose_name='检查判断')),
                ('check_pos', models.CharField(max_length=128, null=True, verbose_name='检查位置')),
            ],
        ),
        migrations.CreateModel(
            name='SelfReport',
            fields=[
                ('example_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='样本序号')),
                ('question', models.TextField(verbose_name='咨询问题')),
                ('diagnose', models.TextField(verbose_name='诊断结果')),
            ],
        ),
        migrations.CreateModel(
            name='TagText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='记录序号')),
                ('example_id', models.IntegerField(verbose_name='样本序号')),
                ('unique_id', models.CharField(max_length=20, verbose_name='样本句子序号')),
                ('sentence_id', models.IntegerField(verbose_name='句子序号')),
                ('speaker', models.TextField(verbose_name='对话人')),
                ('sentence', models.TextField(verbose_name='对话文本')),
                ('label', models.CharField(max_length=300, verbose_name='标签')),
                ('normalized', models.CharField(max_length=128, verbose_name='所有归一化标签')),
                ('type', models.CharField(max_length=128, verbose_name='所有归一化标签特征')),
                ('dialogue_act', models.CharField(default='其他', max_length=128, verbose_name='话语行为')),
                ('report', models.TextField(verbose_name='诊断报告')),
                ('reviewer', models.IntegerField(verbose_name='用户id')),
                ('savedate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户序号')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('start', models.IntegerField(verbose_name='开始序号')),
                ('end', models.IntegerField(verbose_name='结束序号')),
            ],
        ),
    ]
