# Generated by Django 2.2 on 2020-03-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtext',
            name='dialogue_act',
            field=models.CharField(default='其他', max_length=128, null=True, verbose_name='话语行为'),
        ),
        migrations.AlterField(
            model_name='tagtext',
            name='label',
            field=models.CharField(max_length=300, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tagtext',
            name='normalized',
            field=models.CharField(max_length=128, null=True, verbose_name='所有归一化标签'),
        ),
        migrations.AlterField(
            model_name='tagtext',
            name='report',
            field=models.TextField(null=True, verbose_name='诊断报告'),
        ),
        migrations.AlterField(
            model_name='tagtext',
            name='sentence',
            field=models.TextField(null=True, verbose_name='对话文本'),
        ),
        migrations.AlterField(
            model_name='tagtext',
            name='type',
            field=models.CharField(max_length=128, null=True, verbose_name='所有归一化标签特征'),
        ),
        migrations.AlterField(
            model_name='tagtext',
            name='unique_id',
            field=models.CharField(max_length=128, verbose_name='样本句子序号'),
        ),
    ]
